name: Accountr

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Primes
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-folder-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-folder-
    - uses: mstksg/setup-stack@v2
    - name: Install dependencies
      run: |
        stack update
        stack install --only-dependencies
    - name: Build
      run: stack build --fast
    - name: Run tests
      run: stack test
